### ISSUE TITLE
AIDA64 Corsair Link incompatibility

### ISSUE THREAD

**Issue by CovertRockhound** [iJacks1980/FanControl.CommanderPRO#7]
Just a heads up, things get all screwy when using this FanControl plugin and also using AIDA64 with "Corsair Link sensor support" enabled. Speeds bounce around and misreport and stuff similarly to having FanControl and iCUE running at the same time. 

It seems unlikely to me that there will be a way to resolve this. I use AIDA64 for its SensorPanel functionality.

**Comment by iJacks1980** [comment]
Alas there won't be any way around this, as the Commander PRO is essentially a serial device with no checksum data to verify what data has been read back.  If AIDA64 is also trying to read from the Commander PRO (which it does) it will cause issues.  AIDA themselves acknowledge that using AIDA64 and iCUE with the Commander PRO produces bad results - once again it's because of the rather simple nature of the Commander PRO.

The only way around this _might_ be for somebody to develop an AIDA64 Fan Controller plugin - if that is even possible?
